"""Compare potential scores generated by different trained models."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import geopandas as gpd
import pandas as pd
from joblib import load

from urban_growth.scoring.model_comparison import (
    choose_best_model,
    summarize_model_overall,
    summarize_tiers,
    summarize_top_percentiles,
)
from urban_growth.scoring.potential import score_modeling_dataset


def priority_label(priorities: list[int]) -> str:
    if len(priorities) == 1:
        return f"priority_{priorities[0]}"
    return "priorities_" + "_".join(str(priority) for priority in priorities)


def default_modeling_dataset_path(
    country_code: str,
    priorities: list[int],
    grid_size: int,
    start_year: int,
    end_year: int,
) -> Path:
    country = country_code.lower()
    label = priority_label(priorities)

    return (
        Path("data/features/modeling")
        / country
        / f"{grid_size}m"
        / f"{country}_modeling_dataset_{start_year}_{end_year}_{label}_{grid_size}m.parquet"
    )


def default_model_paths() -> dict[str, Path]:
    return {
        "baseline_logistic_regression": Path(
            "models/baselines/baseline_logistic_regression.joblib"
        ),
        "hist_gradient_boosting": Path("models/advanced/hist_gradient_boosting.joblib"),
        "random_forest": Path("models/advanced/random_forest.joblib"),
    }


def parse_model_paths(values: list[str] | None) -> dict[str, Path]:
    if not values:
        return default_model_paths()

    parsed = {}

    for value in values:
        if "=" not in value:
            msg = f"Model paths must use name=path format, received: {value}"
            raise ValueError(msg)

        name, path = value.split("=", maxsplit=1)
        parsed[name] = Path(path)

    return parsed


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Compare potential score models.")
    parser.add_argument("--country-code", default="MX")
    parser.add_argument("--priorities", nargs="+", type=int, default=[1, 2])
    parser.add_argument("--grid-size", type=int, default=500)
    parser.add_argument("--start-year", type=int, default=2016)
    parser.add_argument("--end-year", type=int, default=2024)
    parser.add_argument("--input", type=Path, default=None)
    parser.add_argument(
        "--model-paths",
        nargs="+",
        default=None,
        help="Optional model paths in name=path format.",
    )
    parser.add_argument(
        "--top-percentiles",
        nargs="+",
        type=float,
        default=[0.99, 0.95, 0.90],
    )
    parser.add_argument(
        "--selection-bucket",
        default="top_1pct",
        help="Bucket used to choose the best model.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("reports/model_comparison"),
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    input_path = args.input or default_modeling_dataset_path(
        country_code=args.country_code,
        priorities=args.priorities,
        grid_size=args.grid_size,
        start_year=args.start_year,
        end_year=args.end_year,
    )

    model_paths = parse_model_paths(args.model_paths)

    print(f"Reading modeling dataset: {input_path}")
    frame = gpd.read_parquet(input_path)

    overall_rows = []
    top_rows = []
    tier_rows = []

    for model_name, model_path in model_paths.items():
        print()
        print("=" * 100)
        print(f"Scoring model: {model_name}")
        print(f"Model path: {model_path}")

        model_bundle = load(model_path)
        scored = score_modeling_dataset(frame, model_bundle)

        overall_rows.append(summarize_model_overall(scored, model_name))
        top_rows.extend(
            summarize_top_percentiles(
                scored,
                model_name=model_name,
                percentile_thresholds=args.top_percentiles,
            )
        )
        tier_rows.extend(summarize_tiers(scored, model_name=model_name))

    overall = pd.DataFrame(overall_rows)
    top_percentiles = pd.DataFrame(top_rows)
    tiers = pd.DataFrame(tier_rows)

    best_model = choose_best_model(
        top_percentile_summary=top_percentiles,
        bucket=args.selection_bucket,
    )

    args.output_dir.mkdir(parents=True, exist_ok=True)

    overall_path = args.output_dir / "potential_model_overall_comparison.csv"
    top_path = args.output_dir / "potential_model_top_percentile_comparison.csv"
    tier_path = args.output_dir / "potential_model_tier_comparison.csv"
    summary_path = args.output_dir / "potential_model_selection_summary.json"

    overall.to_csv(overall_path, index=False)
    top_percentiles.to_csv(top_path, index=False)
    tiers.to_csv(tier_path, index=False)
    summary_path.write_text(
        json.dumps(best_model, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    print()
    print("Overall comparison:")
    print(overall.to_string(index=False))

    print()
    print("Top percentile comparison:")
    print(
        top_percentiles.sort_values(
            ["bucket", "recall_of_all_positives", "positive_rate"],
            ascending=[True, False, False],
        ).to_string(index=False)
    )

    print()
    print("Selected model:")
    print(json.dumps(best_model, indent=2, ensure_ascii=False))

    print()
    print(f"Saved overall comparison: {overall_path}")
    print(f"Saved top percentile comparison: {top_path}")
    print(f"Saved tier comparison: {tier_path}")
    print(f"Saved selection summary: {summary_path}")


if __name__ == "__main__":
    main()
